---
- name: Converge
  hosts: redirectors
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
      when: ansible_os_family == 'Debian'
 
  tasks:
    - name: "Include redelk_redir role"
      include_role:
        name: "ansible-role-redelk-redir"
